In [ ]:
import pandas as pd
url = "https://www.sharkattackfile.net/spreadsheets/GSAF5.xls"
sharkattacks = pd.read_excel(url)
display(sharkattacks.head(3))
sharkattacks.shape

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,15 Mar 2024,2024.0,Unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,Brooklyn Sauer,F,13,...,Tiger shark,"Yahoo News, 3/15/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04 Mar 2024,2024.0,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,Matthew White,M,NaN,...,Tiger shark 8',"Surfer, 3/6/2024F",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02 Mar-2024,2024.0,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,NaN,F,11,...,3' to 4' shark,"Hawaii News Now, 3/4/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(6969, 23)

In [ ]:
#Standardizing column names
sharkattacks.columns = [x.strip() for x in sharkattacks.columns]
sharkattacks.columns = [x.lower().replace(' ', '_') for x in sharkattacks.columns]
sharkattacks = sharkattacks.applymap(lambda x:x.lower() if isinstance(x,str) else x)

sharkattacks.columns

Index(['date', 'year', 'type', 'country', 'state', 'location', 'activity',
       'name', 'sex', 'age', 'injury', 'unnamed:_11', 'time', 'species',
       'source', 'pdf', 'href_formula', 'href', 'case_number', 'case_number.1',
       'original_order', 'unnamed:_21', 'unnamed:_22'],
      dtype='object')

In [ ]:
#Cleaning "YEAR" column
sharkattacks["year"].isnull().sum()
year_mode=int(sharkattacks["year"].mode())
sharkattacks["year"].fillna(year_mode,inplace=True)
sharkattacks["year"].isnull().sum()
sharkattacks["year"].unique()
sharkattacks["year"]=sharkattacks["year"].map({x:year_mode if x==0 or x==5 or x==77 or x==1000 else x for x in sharkattacks["year"]})
sharkattacks["year"]=sharkattacks["year"].map({x:year_mode if x==1500 else x for x in sharkattacks["year"]})
sharkattacks["year"].value_counts()
sharkattacks["year"] = sharkattacks["year"].astype(int)

<ipython-input-13-903de30dd422>:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  year_mode=int(sharkattacks["year"].mode())

In [ ]:
#Cleaning "COUNTRY" column
sharkattacks['country'] = sharkattacks['country'].astype(str)
sharkattacks['country'] = sharkattacks['country'].map(lambda x: x.upper())
sharkattacks["country"] = sharkattacks["country"].fillna("UNKNOWN")
sharkattacks["country"] = sharkattacks["country"].str.strip()
sharkattacks["country"] = sharkattacks["country"].replace({"UKNOWN": "UNKNOWN",'nan':"UNKNOWN",'NAN' : "UNKNOWN"})
sharkattacks["country"].nunique()

210

In [ ]:
#Cleaning "LOCATION" column
sharkattacks["location"].isnull().sum()
sharkattacks["location"].fillna("UNKNOWN",inplace=True)
sharkattacks["location"].isnull().sum()
sharkattacks["location"]=sharkattacks["location"].apply(lambda x:x.title())

In [ ]:
#Cleaning "ACTIVITY" column
sharkattacks['activity'] = sharkattacks['activity'].astype(str)
sharkattacks['activity'] = sharkattacks['activity'].map(lambda x: x.title())
sharkattacks["activity"] = sharkattacks["activity"].fillna("UNKNOWN")
sharkattacks["activity"] = sharkattacks["activity"].str.strip()
sharkattacks["activity"] = sharkattacks["activity"].dropna().apply(lambda x: "Fishing" if 'fish' in x else x)
sharkattacks["activity"] = sharkattacks["activity"].dropna().apply(lambda x: "Fishing" if 'Fishing' in x else x)
sharkattacks["activity"] = sharkattacks["activity"].dropna().apply(lambda x: "Fishing" if 'Fish' in x else x)
sharkattacks["activity"] = sharkattacks["activity"].dropna().apply(lambda x: "Fishing" if 'fishing' in x else x)
sharkattacks["activity"] = sharkattacks["activity"].replace({'NAN' : "UNKNOWN", 'Nan' : "UNKNOWN"})

In [ ]:
#Cleaning "SEX" column
sharkattacks['sex'] = sharkattacks['sex'].map({'n': 'm', 'ill': 'm', 'm x 2':'.', '.': '.', 'm': 'm', 'f': 'f'})
sharkattacks['sex'].fillna('m', inplace=True)
sharkattacks= sharkattacks.drop(index=3580)
sharkattacks= sharkattacks.drop(index=6069)
sharkattacks= sharkattacks.drop(index=5568)

In [ ]:
#Cleaning "STATE" column
sharkattacks['state'] = sharkattacks['state'].astype(str)
sharkattacks['state'] = sharkattacks['state'].map(lambda x: x.title())
sharkattacks["state"] = sharkattacks["state"].fillna("UNKNOWN")
sharkattacks["state"] = sharkattacks["state"].str.strip()
sharkattacks["state"] = sharkattacks["state"].replace({"UKNOWN": "UNKNOWN",'nan':"UNKNOWN",'NAN' : "UNKNOWN"})

In [ ]:
#Cleaning "TYPE" column:
sharkattacks["type"].isnull().sum()
sharkattacks["type"].fillna("unidentified", inplace = True)
sharkattacks["type"] = sharkattacks["type"].apply(lambda x: x.strip())
sharkattacks ["type"] = sharkattacks ["type"].replace("?","UNKNOWN")
sharkattacks ["type"] = sharkattacks ["type"].replace("boat","UNKNOWN")

In [ ]:
#Cleaning "NAME" column:
sharkattacks["name"].isnull().sum()
sharkattacks["name"].fillna("UNKNOWN",inplace=True)
sharkattacks["name"].isnull().sum()
sharkattacks["name"].value_counts()
sharkattacks["name"]=sharkattacks["name"].replace("2 males","two males")
sharkattacks["name"]=sharkattacks["name"].apply(lambda x:x.title())

In [ ]:
#Cleaning "INJURY" column:
sharkattacks["injury"].isnull().sum()
sharkattacks["injury"].fillna("UNKNOWN", inplace = True)
sharkattacks["injury"].isnull().sum()
sharkattacks["injury"] = sharkattacks["injury"].apply(lambda x: x.strip())

In [ ]:
#Cleaning "SOURCE" column:
sharkattacks['source'] = sharkattacks['source'].astype(str)
sharkattacks["source"].isnull().sum()
sharkattacks["source"].fillna("UNKNOWN", inplace = True)
sharkattacks["source"].isnull().sum()
sharkattacks["source"] = sharkattacks["source"].apply(lambda x: x.strip())

In [ ]:
#Cleaning "AGE" column:
sharkattacks['age'] = sharkattacks['age'].map({x: str(x).strip(' ') for x in sharkattacks['age']})
sharkattacks['age'] = sharkattacks['age'].map({x:'UNKNOWN' if len(x)>2 else x for x in sharkattacks['age']})
sharkattacks['age'] = sharkattacks['age'].map({x:'UNKNOWN' if not(str(x).isdigit()) else x for x in sharkattacks['age']})
sharkattacks['age'] = sharkattacks['age'].map({x: 28 if x == 'UNKNOWN' else x for x in sharkattacks['age']})
sharkattacks['age'] = sharkattacks['age'].map({x: int(x) if isinstance(x,str) else x for x in sharkattacks['age']})

In [ ]:
#Dropping weird columns:
sharkattacks.drop(columns=["unnamed:_11","unnamed:_21","unnamed:_22","pdf","href_formula","href","case_number","case_number.1","original_order"], inplace=True)

In [ ]:
sharkattacks.head(3)

,date,year,type,country,state,location,activity,name,sex,age,injury,time,species,source
0,15 mar 2024,2024,unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,Brooklyn Sauer,f,13,"minor injuries to back, abdomen and legs",16h00,tiger shark,"yahoo news, 3/15/2024"
1,04 mar 2024,2024,unprovoked,USA,Hawaii,"Old Man'S, Waikiki",Surfing,Matthew White,m,28,"no injury, shark bit surfboard",NaN,tiger shark 8',"surfer, 3/6/2024f"
2,02 mar-2024,2024,unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,Unknown,f,11,lacerations to left foot,13h30,3' to 4' shark,"hawaii news now, 3/4/2024"

In [ ]:
# Printing unique values for all columns to check if the dataset is as clean as possible
for column in sharkattacks.columns:
    unique_values = sharkattacks[column].unique()
    print(f"Unique values in column '{column}':")
    print(unique_values)
    print()

In [ ]:
sharkattacks.to_csv('https://drive.google.com/drive/my-drive/sharkattacks_clean.csv', index=False)

In [ ]:
# Creating a dataframe only for the FISHING, in clolumn ACTIVITY
fishers = sharkattacks.groupby('activity')
fishers = fishers.get_group('Fishing')
fishers.head(1)
fishers.to_csv("fishers.csv")

In [ ]:
# Creating a dataframe only for the COUNTRY clolumn
other_fishers = pd.DataFrame(fishers['country'])
other_fishers.value_counts()
other_fishers_vc = other_fishers['country'].value_counts().reset_index()
sexta_feira = other_fishers_vc[other_fishers_vc["count"]>10]
#sexta_feira.set_index('country')
sexta_feira.set_index("country", drop=True, inplace = True)
sexta_feira

sexta_feira.to_csv("sexta_feira.csv")

In [ ]:
# Creating a dataframe only for the ACTIVITY clolumn
activity = pd.DataFrame(sharkattacks['activity'])
activity.value_counts()
activity_vc = activity['activity'].value_counts().reset_index()
sabado = activity_vc[activity_vc["count"]>10]
sabado.set_index("activity", drop=True, inplace = True)
sabado.to_csv("sabado.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')